### ISSUE TITLE
Service account authorization

### ISSUE THREAD

**Issue by kchugalinskiy** [terraform-providers/terraform-provider-yandex#3]
Hello,

As far as I see, currently there is no support for service account authorization.
My manifest is the following:
```
provider "yandex" {}
resource "yandex_vpc_network" "production" {
  name = "production"
}
```
I've tried to pass service account key id and secret through `YC_CLOUD` and `YC_TOKEN` variables, but the error I've got says
```
* yandex_vpc_network.production: Error while requesting API to create network: request-id = 12dee9f4-74aa-44e9-a882-35089eee859e rpc error: code = InvalidArgument desc = Request validation error: Exactly one of 'yandexPassportOauthToken' and 'jwt' should be specified.
```
Besides it should be mentioned that oauth token works fine, but its TTL is 1 year, which is extremely unsafe for collaborative development, moreover absence of service account authorization makes whole provider useless and not production-ready.

Could you please take care of this issue, or let's discuss how I could help you to fix it.

**Comment by GennadySpb** [comment]
Hello! 

Currently, the provider does not support authentication on behalf of service account.
I agree that this is a necessary feature and will be accepted for implementation soon.

**Comment by GennadySpb** [comment]
Please, check release [v0.2.0](https://github.com/terraform-providers/terraform-provider-yandex/releases/tag/v0.2.0): there is support for service account authorization.

Link to [documentation](https://www.terraform.io/docs/providers/yandex/index.html#service_account_key_file).
